M48
; DRILL file {KiCad (6.0.2)} date Thu Feb 24 13:51:01 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-24T13:51:01+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X1.7126Y-0.8858
X1.7126Y-4.1535
X4.9803Y-4.1535
X4.9803Y-0.8858
T0
M30
